# Generated by Django 5.0.3 on 2024-03-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
