# Generated by Django 5.0.3 on 2024-05-09 09:10

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_alter_cart_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.CarouselItems.image_path, verbose_name='Изображение')),
                ('caption', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Корзина'},
        ),
    ]
