# Generated by Django 5.0.3 on 2024-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_carouselitems_alter_cart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitems',
            name='caption',
        ),
        migrations.AddField(
            model_name='carouselitems',
            name='title',
            field=models.CharField(max_length=60, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='carouselitems',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
